### ISSUE TITLE
Versions visibility + handling multiple versions

### ISSUE THREAD

**Issue by romsson** [LyonDataViz/occupapp#23]
-Show which version of the app is currently used
-Enable to load previous versions (URL?)
-Link version to Github milestone page? or release?
https://github.com/severo/occupapp/releases/tag/v1.1.0
https://github.com/severo/occupapp/milestone/3

**Comment by severo** [comment]
Simplest implementation in https://github.com/LyonDataViz/occupapp/pull/31.

**Comment by severo** [comment]
Add a link to the corresponding commit.
Put in a "popup"

**Comment by severo** [comment]
More details from #43 about the commit number:

> It would be convenient to add a build or commit number we can use when reporting bugs so we can rollback to this particular version

**Comment by severo** [comment]
Bump to v1.3.0

**Comment by severo** [comment]
Done:

- detail of the versions in the README: https://github.com/LyonDataViz/occupapp#versions
- more detail in https://github.com/LyonDataViz/occupapp/blob/master/CHANGELOG.md (and former file VERSIONS.md has been removed)
- sidetab footer contains the version and the last commit, with links (see at https://occupapp-pvm53kc77.now.sh/ for example). It works both locally and on now.sh, even if it required different code (see https://github.com/LyonDataViz/occupapp/blob/master/vue.config.js).
