### ISSUE TITLE
Feedback/Suggestion/Infos buttons

### ISSUE THREAD

**Issue by romsson** [LyonDataViz/occupapp#24]
Feedback -> Google Form? Then direct notifications + handling in a spreadsheet
Suggestions -> Link to issues? https://github.com/severo/occupapp/issues
Infos -> MI2? https://projet.liris.cnrs.fr/mi2/

Regarding where to put them, probably within the hamburger menu panel (left) + icons

**Comment by severo** [comment]
To be done:

> Feedback -> Google Form? Then direct notifications + handling in a spreadsheet

**Comment by severo** [comment]
Bump to v1.3.0
