### ISSUE TITLE
Browse image list

### ISSUE THREAD

**Issue by romsson** [LyonDataViz/occupapp#25]
The left panel shows the image list, but what if the list is longer than the height of the page? Scroll down I guess.

**Comment by severo** [comment]
Fixed: the image list is in a modal box, and a scroll bar appears if the list is bigger than the available space.

![Capture d’écran de 2019-12-16 10-42-45](https://user-images.githubusercontent.com/1676121/70896352-d4249200-1ff0-11ea-8a11-d5de53796ed1.png)
