### ISSUE TITLE
When loading on iPhone the panel is open

### ISSUE THREAD

**Issue by romsson** [LyonDataViz/occupapp#42]
Should probably be closed?

It's not a problem on a Desktop as there is enough space and panel does not prevent adding points (like it does on the phone)

Then a solution might to detect when mobile and set it to closed

![image](https://user-images.githubusercontent.com/586236/71087049-88fab280-219b-11ea-81a7-e3450b54fed4.png)

**Comment by severo** [comment]
Yes, sure!

**Comment by severo** [comment]
Fixed
