### ISSUE TITLE
Rotation issue with images taken with a phone

### ISSUE THREAD

**Issue by romsson** [LyonDataViz/occupapp#45]
There might be some EXIF rotation information to extract from the image using JavaScript on the client side?

![image](https://user-images.githubusercontent.com/586236/71087395-5bfacf80-219c-11ea-9c42-3a9c34b53ffb.png)

**Comment by severo** [comment]
Not that simple. First analysis:

The orientation is coded in the EXIF Orientation field. This field is obviously not always present. It has a value between 1 and 8. See https://leancrew.com/all-this/2009/04/derotating-jpegs-with-exiftool/ and http://sylvana.net/jpegcrop/exif_orientation.html for more details.

Browsers manage this field differently.

Safari always respects the field, and there is no way to change this behavior, ie. it considers the EXIF Orientation field as part of the image format, and the data available in the loaded image are the data of the rotated image.

Firefox does not respect the field when loading the image by default, but allows to do it with the [`image-orientation: from-image`](https://drafts.csswg.org/css-images-3/#the-image-orientation) CSS3 property.

Until now, if I understand correctly, Chromium does the same as Firefox, but doesn't implement `image-orientation`. And the situation will [change soon]([Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=158753): it should work the same as Safari (respect EXIF by default), and also implement the `image-orientation` CSS property, setting its default value to `from-image` (contrarily to Firefox and the CSS3 standard).

Finally, note that the `image-orientation` CSS property seems to have [disappeared from CSS4](https://drafts.csswg.org/css-images-4/#image-notation), and the default behavior should then be to always respect the EXIF metadata by default (ie. without having to add code to manage this).

**Comment by severo** [comment]
Also: I noted that when taking a selfie, ie. using my front camera, the image is mirrored vertically. There is a need to also manage this.

**Comment by severo** [comment]
Maybe the solution is to used https://www.npmjs.com/package/blueimp-load-image when uploading pictures, and then store the image as a base64 string (as we already do).

**Comment by severo** [comment]
An example of rotated and mirrored image:

![Landscape_5](https://user-images.githubusercontent.com/1676121/71097214-f0226200-21af-11ea-851f-f2cf2d5ae669.jpg)

~~~
identify -verbose Landscape_5.jpg | grep exif
~~~

~~~
    exif:Orientation: 5
    exif:ResolutionUnit: 2
    exif:XResolution: 72/1
    exif:YCbCrPositioning: 1
    exif:YResolution: 72/1
    Profile-exif: 96 bytes
~~~

When loaded in Chromium and Firefox with blueimp-load-image using their demo: https://blueimp.github.io/JavaScript-Load-Image/, it is shown as expected:

- Firefox:

![Capture d’écran de 2019-12-18 16-05-56](https://user-images.githubusercontent.com/1676121/71097447-468fa080-21b0-11ea-9fab-ed1514c186b4.png)

- Chromium:

![Capture d’écran de 2019-12-18 16-07-13](https://user-images.githubusercontent.com/1676121/71097568-7474e500-21b0-11ea-998e-2ed1626dbb76.png)

@Fil or @romsson: could you try with Safari? 1. Download https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Landscape_5.jpg, 2. Upload to https://blueimp.github.io/JavaScript-Load-Image/ in Safari, 3. Upload a screenshot here.

**Comment by Fil** [comment]
![Capture d’écran 2019-12-18 à 16 27 49](https://user-images.githubusercontent.com/7001/71099333-64aad000-21b3-11ea-88d0-520f6c01d512.png)

**Comment by severo** [comment]
YES!

**Comment by severo** [comment]
Should be fixed.

![Capture d’écran de 2019-12-18 17-40-49](https://user-images.githubusercontent.com/1676121/71105258-86a95000-21bd-11ea-8c45-83e0b2cbdd7e.png)
