### ISSUE TITLE
Show the list of agents

### ISSUE THREAD

**Issue by severo** [LyonDataViz/occupapp#5]
Show list of agents with attributes (color, name) that can be modified by the user.

Note that a color correspond to at least an image overlay color and a symbol color

**Comment by romsson** [comment]
When and where to show the list? I suggest once one clicks on the hamburger menue, then show the list + stats (from #7 as full screen)

**Comment by romsson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Show the list of agents](https://trello.com/c/ahfgNdIE/127-show-the-list-of-agents)

**Comment by severo** [comment]
The list of agents is shown. As decided with the team, it's better not to edit the values there, but to add another panel dedicated to the edition. See #35
