### ISSUE TITLE
Upload an image

### ISSUE THREAD

**Issue by severo** [LyonDataViz/occupapp#9]

**Comment by severo** [comment]
See https://observablehq.com/d/83df2e37a3788730

**Comment by Fil** [comment]
https://github.com/severo/observable-to-standalone/issues/13

**Comment by severo** [comment]
In particular, ensure it's possible to upload a picture just taken from a Tablet/Cellphone camera

**Comment by severo** [comment]
OK, done. webcam work is in #20
